branches:
  only:
  - appveyor
skip_tags: true
environment:
  AUTOMATED_TESTING: 1
platform:
  - x86
install:
  - bash --version
  - bash -c 'date -u; uname -a'
  - set PATH=C:\Mingw\bin;C:\Mingw\MSYS\1.0\bin;%PATH%
##   - C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P file-devel -P libpcre-devel
## # -P wget
##   - set PATH=C:\cygwin\bin;%PATH%
##   - echo %PATH%
##   - bash --version
##   - bash -c 'uname -a'
## #  - bash -c 'mkdir -p /www/example/products'
## #  - bash -c 'ls -ld / /www /www/example /www/example/products'
## #  - bash -c 'ls -l /www/example/products'
## #  - bash -c 'echo "test text document" | tee /www/example/products/text.txt'
## #  - bash -c 'echo "<html><head><title>HTML Title</title><body>test HTML document</body></html>" | tee /www/example/products/html.htm'
## #  - bash -c 'wget http://easychair.org/publications/easychair-libreoffice.docx -O /www/example/products/example.docx'
## #  - bash -c 'wget https://www.fpsct.org/uploaded/FHS/Library/How_to_use_Wikipedia_effectively.doc -O /www/example/products/sample.doc'
## #  - bash -c 'ls -l /www/example/products'
  - echo %PATH%
  - bash -c "echo 'c:/mingw /mingw' >> /etc/fstab"
  - type c:\mingw\msys\1.0\etc\fstab
  - bash -c 'mingw-get install libz-dev'
  - bash -c 'ls -l c:/mingw/bin/*wget*; exit 0'
build_script:
  - echo %PATH%
  - set PATH=C:\Mingw\bin;C:\Mingw\MSYS\1.0\bin;%PATH%
  - bash -c 'pwd;ls -l'
  - bash -c 'time ./bootstrap xapian-core xapian-applications/omega'
  - bash -c 'pwd;ls -l'
  - bash -c 'time ./configure --disable-documentation < /dev/null'
  - bash -c 'pwd;ls -l'
  - bash -c 'time make -k -sj2 V=0 < /dev/null'
test_script:
  - bash -c 'time make -k check VERBOSE=1 < /dev/null'
#  - bash -c 'xapian-applications/omega/omindex -v --db omtest.db --url msproducts /www/example/products/'
#  - bash -c 'xapian-core/bin/xapian-delve omtest.db'
